#!/usr/bin/env bash
set -euo pipefail

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
out="$here/dist"

usage() {
  cat <<EOF
generate.sh — render the kitty, btop, matplotlib, Claude Code and opencode themes
out of ddlc-palette

Render dist/ from ddlc-palette. Run it after the palette moves and commit both

  --light FILE     base16-ddlc-light.yaml   (or \$DDLC_BASE16_LIGHT)
  --dark FILE      base16-ddlc-dark.yaml    (or \$DDLC_BASE16_DARK)
  --palette FILE   palette.env              (or \$DDLC_PALETTE_ENV)

All three come from ddlc-palette, and nix develop puts them in the environment already.
Without Nix, take them from the palette repository:

  curl -sSLO https://raw.githubusercontent.com/rokokol/ddlc-palette/master/dist/base16-ddlc-dark.yaml
  curl -sSLO https://raw.githubusercontent.com/rokokol/ddlc-palette/master/dist/palette.env
EOF
}

declare -A scheme=(
  [light]="${DDLC_BASE16_LIGHT:-}"
  [dark]="${DDLC_BASE16_DARK:-}"
)
palette_env="${DDLC_PALETTE_ENV:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --light)
      scheme[light]="${2:?file required}"
      shift 2
      ;;
    --dark)
      scheme[dark]="${2:?file required}"
      shift 2
      ;;
    --palette)
      palette_env="${2:?file required}"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 1
      ;;
  esac
done

# The kitty and btop tables below name base16 slots, so resolve them once per variant. $V picks
# the variant
declare -A slot
for variant in light dark; do
  file="${scheme[$variant]}"
  [ -n "$file" ] || {
    echo "generate.sh: no $variant scheme — pass --$variant or set DDLC_BASE16_${variant^^}" >&2
    exit 1
  }
  n=0
  while read -r key hex; do
    slot["$variant/$key"]="$hex"
    n=$((n + 1))
  done < <(sed -n 's/^  \(base[0-9A-F][0-9A-F]\): "\(#[0-9A-F]\{6\}\)".*/\1 \2/p' "$file")
  # Sixteen slots or it is not a base16 scheme, and a half-read file would render a half-theme
  [ "$n" = 16 ] || {
    echo "generate.sh: $file has $n slots, want 16" >&2
    exit 1
  }
done
s() { printf '%s' "${slot["$V/$1"]}"; }

# The other themes have more roles than sixteen slots, so their tables name palette colours
# directly and resolve against the flat name=HEX form. The hex comes in bare — matplotlib wants
# it that way (its parser treats the rest of an rcparam value after a "#" as a comment, so a
# quoted "#BB5599" reads as an unterminated string and the whole cycler is silently discarded
# for the stock one) — and the JSON writers put the "#" back on
[ -n "$palette_env" ] || {
  echo "generate.sh: no palette — pass --palette or set DDLC_PALETTE_ENV" >&2
  exit 1
}
declare -A pal
pal_names=()
while read -r name hex; do
  pal[$name]="$hex"
  pal_names+=("$name")
done < <(sed -n 's/^\([A-Za-z][A-Za-z0-9]*\)=\([0-9A-F]\{6\}\)$/\1 \2/p' "$palette_env")
[ "${#pal_names[@]}" -gt 0 ] || {
  echo "generate.sh: $palette_env holds no name=HEX lines" >&2
  exit 1
}

# A table naming a colour the palette does not have is a typo or a rename that got away. Either
# would ship a theme with a hole in it, so refuse the whole run before writing any of it
need() { # <theme> <name>...
  local theme="$1" name
  shift
  for name in "$@"; do
    [[ $name == "-" || $name == "none" || -n ${pal[$name]:-} ]] || {
      echo "generate.sh: $theme names $name, which the palette does not have" >&2
      exit 1
    }
  done
}

mkdir -p "$out"
banner="Generated by generate.sh from ddlc-palette's base16 schemes — do not edit"
named_banner="Generated by generate.sh from ddlc-palette's colours — do not edit"

for V in light dark; do

  # Slot for slot the mapping tinted-theming/tinted-kitty uses, with one departure: it grounds
  # the selection in base03, which leaves base05 on it at 1.65:1 here, so base02 carries it
  {
    echo "# $banner"
    echo "# vim:ft=kitty"
    echo "# Include this from kitty.conf: include ddlc-kitty-$V.conf"
    echo
    echo "background $(s base00)"
    echo "foreground $(s base05)"
    echo "selection_background $(s base02)"
    echo "selection_foreground $(s base05)"
    echo "cursor $(s base05)"
    echo "cursor_text_color $(s base00)"
    echo "url_color $(s base04)"
    echo "active_border_color $(s base03)"
    echo "inactive_border_color $(s base01)"
    echo "wayland_titlebar_color $(s base00)"
    echo "macos_titlebar_color $(s base00)"
    echo "active_tab_background $(s base00)"
    echo "active_tab_foreground $(s base05)"
    echo "inactive_tab_background $(s base01)"
    echo "inactive_tab_foreground $(s base04)"
    echo "tab_bar_background $(s base01)"
    echo
    while read -r n slot_name; do echo "color$n $(s "$slot_name")"; done <<'ANSI'
0 base00
1 base08
2 base0B
3 base0A
4 base0D
5 base0E
6 base0C
7 base05
8 base02
9 base08
10 base0B
11 base0A
12 base0D
13 base0E
14 base0C
15 base07
16 base09
17 base0F
18 base01
19 base02
20 base04
21 base06
ANSI
  } >"$out/ddlc-kitty-$V.conf"

  # btop has no base16 template anywhere upstream, so this mapping is ours. Meters that carry no
  # scale are one colour — btop reads that as a start with an empty mid and end
  {
    echo "# $banner"
    echo "# Drop into ~/.config/btop/themes/ and select it with color_theme=\"ddlc-$V\""
    echo
    echo "theme[main_bg]=\"$(s base00)\""
    echo "theme[main_fg]=\"$(s base05)\""
    echo "theme[title]=\"$(s base06)\""
    echo "theme[hi_fg]=\"$(s base0A)\""
    echo "theme[selected_bg]=\"$(s base02)\""
    echo "theme[selected_fg]=\"$(s base06)\""
    echo "theme[inactive_fg]=\"$(s base03)\""
    echo "theme[graph_text]=\"$(s base04)\""
    echo "theme[meter_bg]=\"$(s base01)\""
    echo "theme[proc_misc]=\"$(s base0B)\""
    echo "theme[cpu_box]=\"$(s base0D)\""
    echo "theme[mem_box]=\"$(s base0B)\""
    echo "theme[net_box]=\"$(s base0E)\""
    echo "theme[proc_box]=\"$(s base0C)\""
    echo "theme[div_line]=\"$(s base03)\""
    # Load rises through the palette's warm accents: green, then yellow, then red
    for gradient in temp cpu process; do
      echo "theme[${gradient}_start]=\"$(s base0B)\""
      echo "theme[${gradient}_mid]=\"$(s base0A)\""
      echo "theme[${gradient}_end]=\"$(s base08)\""
    done
    while read -r meter slot_name; do
      echo "theme[${meter}_start]=\"$(s "$slot_name")\""
      echo "theme[${meter}_mid]=\"\""
      echo "theme[${meter}_end]=\"\""
    done <<'METERS'
free base0B
cached base0C
available base0A
used base08
download base0D
upload base0E
METERS
  } >"$out/ddlc-btop-$V.theme"

done

# --- matplotlib -------------------------------------------------------------------------------
# matplotlib finds a named style by filename under stylelib/, so the file name is the API:
# plt.style.use("ddlc"). The module name is too — import ddlc_cmaps — hence its underscore

mpl_cycle_light="plum bow rule monikaEye yuri"
mpl_cycle_dark="plum bow rule"
# shellcheck disable=SC2086 # the cycles are word lists on purpose
need matplotlib paper ink jacket ash yuri dot pink sayoriEye skirt bow bowShadow sayori \
  $mpl_cycle_light $mpl_cycle_dark

mpl_cycler() {
  local sep='' cyc='' c
  for c in "$@"; do
    cyc+="$sep'${pal[$c]}'"
    sep=', '
  done
  printf "axes.prop_cycle:  cycler('color', [%s])\n" "$cyc"
}

mpl_colours() { # ground ink muted grid
  cat <<EOF
figure.facecolor:  ${pal[$1]}
savefig.facecolor: ${pal[$1]}
axes.facecolor:    ${pal[$1]}
axes.edgecolor:    ${pal[$4]}
grid.color:        ${pal[$4]}

text.color:        ${pal[$2]}
axes.labelcolor:   ${pal[$2]}
axes.titlecolor:   ${pal[$2]}
xtick.color:       ${pal[$3]}
ytick.color:       ${pal[$3]}
xtick.labelcolor:  ${pal[$2]}
ytick.labelcolor:  ${pal[$2]}
EOF
}

# No axes.grid in here: it would mean "on every axes", and a heatmap or an image draws above
# the grid whatever axisbelow says, so the lines end up cutting across the data. A chart that
# wants one calls ax.grid(axis="y") for the direction its values actually run
mpl_common() {
  cat <<'EOF'
figure.dpi:          140
savefig.dpi:         140
savefig.bbox:        tight
font.size:           9
axes.titlesize:      11
axes.titleweight:    bold
axes.titlelocation:  left
axes.spines.top:     False
axes.spines.right:   False
axes.axisbelow:      True
grid.linewidth:      0.7
legend.frameon:      False
lines.linewidth:     1.8
EOF
}

{
  echo "# $named_banner"
  echo "# Copy into ~/.config/matplotlib/stylelib/ and select it: plt.style.use(\"ddlc\")"
  echo
  echo "# A chart assigns series from this list in order, and the order is the safety mechanism"
  echo "# rather than a taste: adjacent entries are what a stacked bar or a multi-line chart puts"
  echo "# side by side. Each neighbour pair clears deuteranopia and protanopia"
  echo "# (Machado-Oliveira-Fernandes 2009 at severity 1.0) by OKLab distance x100 >= 8, and"
  echo "# >= 15 unsimulated. Reordering is a visible change even though no colour moves"
  # shellcheck disable=SC2086 # the cycle is a word list on purpose
  mpl_cycler $mpl_cycle_light
  echo
  mpl_colours paper ink jacket ash
  echo
  mpl_common
} >"$out/ddlc.mplstyle"

{
  echo "# $named_banner"
  echo "# Copy into ~/.config/matplotlib/stylelib/ and select it: plt.style.use(\"ddlc-dark\")"
  echo
  echo "# Three series, not five. The palette is polarised — the same reason base16 draws"
  echo "# different accents per variant — and everything else either leaves the dark lightness"
  echo "# band or falls under 3:1 on ink"
  # shellcheck disable=SC2086 # the cycle is a word list on purpose
  mpl_cycler $mpl_cycle_dark
  echo
  mpl_colours ink paper jacket yuri
  echo
  mpl_common
} >"$out/ddlc-dark.mplstyle"

# A colormap is an object, not an rcparam, so it cannot live in a .mplstyle. Importing the
# module registers the four by name, after which they are strings like any built-in
cat >"$out/ddlc_cmaps.py" <<EOF
# $named_banner
"""DDLC colormaps for matplotlib, registered by name.

import ddlc_cmaps  # noqa: F401 — registers on import
plt.imshow(data, cmap="ddlc_seq")

Sequential runs one hue toward the foreground of its ground, so more-is-darker on paper and
more-is-lighter on ink. Diverging is two one-hue arms about a neutral middle, so "no
difference" reads as nothing at all; its midpoint is the only grey in each.
"""

from matplotlib.colors import LinearSegmentedColormap
from matplotlib import colormaps

_MAPS = {
    "ddlc_seq": ["#${pal[dot]}", "#${pal[pink]}", "#${pal[plum]}"],
    "ddlc_seq_dark": ["#${pal[plum]}", "#${pal[pink]}", "#${pal[dot]}"],
    "ddlc_div": [
        "#${pal[yuri]}",
        "#${pal[rule]}",
        "#${pal[ash]}",
        "#${pal[bow]}",
        "#${pal[bowShadow]}",
    ],
    "ddlc_div_dark": [
        "#${pal[sayoriEye]}",
        "#${pal[skirt]}",
        "#${pal[jacket]}",
        "#${pal[bow]}",
        "#${pal[sayori]}",
    ],
}

for _name, _colours in _MAPS.items():
    for _key, _steps in ((_name, _colours), (_name + "_r", _colours[::-1])):
        if _key not in colormaps:
            colormaps.register(LinearSegmentedColormap.from_list(_key, _steps))
EOF

# --- report css -------------------------------------------------------------------------------
# The matplotlib roles, spoken in CSS for an HTML report: the same grounds, the same grid
# discipline, the same series — five on paper, three on ink, for the mplstyle's own reason.
# The element choices follow the site itself: links plum with a pink hover, dividers blush,
# neutral rules ash. Light is the default; dark answers prefers-color-scheme and an explicit
# data-theme wins over both

need report paper ink jacket ash dot blush pink plum yuri yuriShadow bow rule monikaEye

css_light_tokens() {
  cat <<EOF
  --ddlc-ground: #${pal[paper]};
  --ddlc-ink: #${pal[ink]};
  --ddlc-muted: #${pal[jacket]};
  --ddlc-grid: #${pal[ash]};
  --ddlc-divider: #${pal[blush]};
  --ddlc-accent: #${pal[plum]};
  --ddlc-accent-live: #${pal[pink]};
  --ddlc-code-ground: #${pal[dot]};
  --ddlc-selection: #${pal[blush]};
  --ddlc-inform-ground: #${pal[dot]};
  --ddlc-inform-border: #${pal[blush]};
  --ddlc-series-1: #${pal[plum]};
  --ddlc-series-2: #${pal[bow]};
  --ddlc-series-3: #${pal[rule]};
  --ddlc-series-4: #${pal[monikaEye]};
  --ddlc-series-5: #${pal[yuri]};
EOF
}

css_dark_tokens() {
  cat <<EOF
  --ddlc-ground: #${pal[ink]};
  --ddlc-ink: #${pal[paper]};
  --ddlc-muted: #${pal[jacket]};
  --ddlc-grid: #${pal[yuri]};
  --ddlc-divider: #${pal[yuri]};
  --ddlc-accent: #${pal[pink]};
  --ddlc-accent-live: #${pal[blush]};
  --ddlc-code-ground: #${pal[yuriShadow]};
  --ddlc-selection: #${pal[yuri]};
  --ddlc-inform-ground: #${pal[yuriShadow]};
  --ddlc-inform-border: #${pal[yuri]};
  --ddlc-series-1: #${pal[plum]};
  --ddlc-series-2: #${pal[bow]};
  --ddlc-series-3: #${pal[rule]};
  --ddlc-series-4: #${pal[jacket]};
  --ddlc-series-5: #${pal[jacket]};
EOF
}

{
  echo "/* $named_banner"
  echo "   The DDLC matplotlib theme as a stylesheet for HTML reports: link it and write prose."
  echo "   Light by default, dark under prefers-color-scheme, data-theme=\"dark|light\" wins."
  echo "   A dark report gets three series where a light one gets five — the palette is"
  echo "   polarised, and the other two do not survive on ink; there --ddlc-series-4 and -5"
  echo "   collapse into the muted grey on purpose, so a tail that was not folded into the"
  echo "   remaining three is visible but stops pretending to be a series."
  echo "   The inform block is the game's own dialog box: a dot ground under the ink"
  echo "   with a blush frame in light, yuriShadow under a yuri frame on dark — the"
  echo "   level lives in the frame, not in a hue the palette does not have */"
  echo
  echo ":root {"
  css_light_tokens
  echo "}"
  echo
  echo "@media (prefers-color-scheme: dark) {"
  echo "  :root:not([data-theme=\"light\"]) {"
  css_dark_tokens | sed 's/^/  /'
  echo "  }"
  echo "}"
  echo
  echo "[data-theme=\"dark\"] {"
  css_dark_tokens
  echo "}"
  echo
  cat <<'CSS'
body {
  background: var(--ddlc-ground);
  color: var(--ddlc-ink);
  font-size: 1rem;
  line-height: 1.55;
  max-width: 46rem;
  margin: 0 auto;
  padding: 2rem 1.25rem 4rem;
}

/* Bold, left, a step over the body — the mplstyle's title, spelled for a page */
h1, h2, h3, h4 {
  color: var(--ddlc-ink);
  font-weight: bold;
  text-align: left;
  line-height: 1.25;
}

h1 {
  border-bottom: 2px solid var(--ddlc-divider);
  padding-bottom: 0.3rem;
}

a {
  color: var(--ddlc-accent);
}

a:hover {
  color: var(--ddlc-accent-live);
}

::selection {
  background: var(--ddlc-selection);
}

hr {
  border: 0;
  border-top: 2px solid var(--ddlc-divider);
}

/* The grid stays under the data here too: rules between rows only, no vertical lines */
table {
  border-collapse: collapse;
}

th, td {
  text-align: left;
  padding: 0.3rem 1rem 0.3rem 0;
  border-bottom: 1px solid var(--ddlc-grid);
}

th {
  border-bottom-color: var(--ddlc-muted);
}

code, pre {
  background: var(--ddlc-code-ground);
  border-radius: 4px;
}

code {
  padding: 0.1em 0.3em;
}

pre {
  padding: 0.75rem 1rem;
  overflow-x: auto;
}

pre code {
  padding: 0;
}

blockquote {
  margin-left: 0;
  padding-left: 1rem;
  border-left: 3px solid var(--ddlc-accent);
  color: var(--ddlc-muted);
}

/* The one block allowed to interrupt, shaped like the game's own dialog box:
   a pink ground framed on all sides, everything centred, the ink doing the
   talking */
.ddlc-inform {
  background: var(--ddlc-inform-ground);
  border: 2px solid var(--ddlc-inform-border);
  border-radius: 6px;
  padding: 1.25rem 1.5rem;
  text-align: center;
  color: var(--ddlc-ink);
}

figcaption, .ddlc-muted {
  color: var(--ddlc-muted);
  font-size: 0.9em;
}

.ddlc-series-1 { color: var(--ddlc-series-1); }
.ddlc-series-2 { color: var(--ddlc-series-2); }
.ddlc-series-3 { color: var(--ddlc-series-3); }
.ddlc-series-4 { color: var(--ddlc-series-4); }
.ddlc-series-5 { color: var(--ddlc-series-5); }
CSS
} >"$out/ddlc-report.css"

# --- Claude Code ------------------------------------------------------------------------------
# Claude Code reads a theme from ~/.claude/themes/<slug>.json: a base theme plus overrides, and
# it drops any key its version does not know without saying so. A slot reading "-" keeps
# whatever the base theme paints, because the palette holds nothing for it: the site ships no
# light green, so the light variant cannot colour an added line.
# The dark variant leans into the same slots ddlc.nvim draws from base16 dark: blush for the
# page text, neon pink for the frames and modes, sayoriEye and monikaEye for the cold and the
# green accents. The light variant sits on the colours that actually read on paper — the warm
# pastels fall under 3:1 there, so plum carries the claude identity and bowShadow the warning.
# Contrast holds every foreground slot: on ink, blush 10.3:1, natsuki 10.0, sayoriEye 9.2,
# sayori 8.1, monikaEye 7.3, jacket 6.2, monika 5.8, pink 5.6, plum 3.7, rule 3.2; on paper,
# yuriShadow 15.3, ribbon 6.2, bow 5.8, skirt 5.7, rule 5.0, plum 4.3
claude_code_slots="
text                                  blush       yuriShadow
inverseText                           ink         paper
inactive                              jacket      jacket
inactiveShimmer                       ash         ash
subtle                                natsuki     jacket
promptBorder                          pink        blush
promptBorderShimmer                   blush       pink
claude                                sayori      plum
claudeShimmer                         natsuki     pink
claudeBlue_FOR_SYSTEM_SPINNER         rule        skirt
claudeBlueShimmer_FOR_SYSTEM_SPINNER  sayoriEye   rule
clawd_body                            bow         bow
clawd_background                      yuriShadow  dot
permission                            sayoriEye   skirt
permissionShimmer                     rule        rule
suggestion                            rule        rule
remember                              pink        plum
ide                                   sayoriEye   skirt
autoAccept                            pink        plum
autoAcceptShimmer                     blush       pink
skill                                 plum        plum
merged                                plum        plum
effortUltra                           pink        pink
bashBorder                            pink        pink
planMode                              monikaEye   ribbon
success                               monikaEye   ribbon
warning                               monika      bowShadow
warningShimmer                        sayori      monika
error                                 bow         bow
diffAdded                             ribbon      -
diffRemoved                           bowShadow   -
diffAddedWord                         monikaEye   ribbon
diffRemovedWord                       bow         bowShadow
selectionBg                           yuri        blush
userMessageBackground                 yuriShadow  dot
userMessageBackgroundHover            yuri        blush
composerSidebarBackground             yuriShadow  dot
bashMessageBackgroundColor            yuriShadow  dot
memoryBackgroundColor                 yuriShadow  dot
rate_limit_fill                       pink        plum
rate_limit_empty                      yuriShadow  blush
fastMode                              sayori      plum
fastModeShimmer                       natsuki     pink
briefLabelYou                         sayoriEye   skirt
briefLabelClaude                      sayori      plum
red_FOR_SUBAGENTS_ONLY                bow         bow
orange_FOR_SUBAGENTS_ONLY             sayori      sayori
yellow_FOR_SUBAGENTS_ONLY             monika      monika
green_FOR_SUBAGENTS_ONLY              monikaEye   ribbon
cyan_FOR_SUBAGENTS_ONLY               sayoriEye   rule
blue_FOR_SUBAGENTS_ONLY               rule        skirt
purple_FOR_SUBAGENTS_ONLY             plum        yuri
pink_FOR_SUBAGENTS_ONLY               natsuki     pink
professionalBlue                      skirt       skirt
chromeYellow                          monika      monika
"

while read -r cc_slot cc_dark cc_light; do
  need "claude-code slot $cc_slot" "$cc_dark" "$cc_light"
done < <(awk 'NF == 3' <<<"$claude_code_slots")

# JSON takes no comment, so the banner goes in a field. Claude Code reads name, base and
# overrides and ignores the rest, so it costs nothing to say where the file came from
for variant in dark light; do
  col=2
  [[ $variant == light ]] && col=3
  awk -v c="$col" 'NF == 3 && $c != "-" { print $1 "\t" $c }' <<<"$claude_code_slots" |
    while read -r cc_slot cc_name; do printf '%s\t#%s\n' "$cc_slot" "${pal[$cc_name]}"; done |
    jq -Rn --arg banner "$named_banner" --arg name "DDLC $variant" --arg base "$variant" '{
      _generated: $banner,
      name: $name,
      base: $base,
      overrides: ([inputs | split("\t") | { key: .[0], value: .[1] }] | from_entries)
    }' >"$out/ddlc-claude-code-$variant.json"
done

# --- opencode ---------------------------------------------------------------------------------
# opencode takes one file for both variants: a value is either one colour or {dark, light}, and
# a string that is not a hex is a reference into defs — so defs carries the palette by name and
# the theme reads like the tables above. Its schema allows nothing extra (additionalProperties
# is false at the top and in theme), so there is no banner field and no key beyond the schema's
# own; defs naming the palette is the provenance the file carries. "none" is the schema's word
# for the terminal's own colour — the light diff backgrounds take it for the reason the
# claude-code light diff slots read "-". The light column stays off the warm pastels — they
# fall under 3:1 on paper — and the dark one keeps its quiet roles a step brighter than
# claude-code's, because opencode paints whole panels with them
opencode_slots="
primary                    pink        plum
secondary                  sayoriEye   skirt
accent                     sayori      plum
error                      bow         bow
warning                    monika      bowShadow
success                    monikaEye   ribbon
info                       sayoriEye   skirt
text                       dot         yuriShadow
textMuted                  natsuki     jacket
selectedListItemText       paper       paper
background                 ink         paper
backgroundPanel            yuriShadow  dot
backgroundElement          yuri        natsuki
border                     jacket      jacket
borderActive               pink        plum
borderSubtle               yuri        ash
diffAdded                  paper       ribbon
diffRemoved                paper       bowShadow
diffContext                jacket      jacket
diffHunkHeader             jacket      jacket
diffHighlightAdded         monikaEye   ribbon
diffHighlightRemoved       bow         bowShadow
diffAddedBg                ribbon      none
diffRemovedBg              bowShadow   none
diffContextBg              none        none
diffLineNumber             jacket      jacket
diffAddedLineNumberBg      ribbon      none
diffRemovedLineNumberBg    bowShadow   none
markdownText               dot         yuriShadow
markdownHeading            pink        plum
markdownLink               rule        rule
markdownLinkText           sayoriEye   skirt
markdownCode               natsuki     plum
markdownBlockQuote         jacket      jacket
markdownEmph               monika      yuri
markdownStrong             sayori      plum
markdownHorizontalRule     yuriShadow  ash
markdownListItem           dot         yuriShadow
markdownListEnumeration    pink        plum
markdownImage              rule        rule
markdownImageText          sayoriEye   skirt
markdownCodeBlock          dot         yuriShadow
syntaxComment              jacket      jacket
syntaxKeyword              pink        plum
syntaxFunction             sayoriEye   skirt
syntaxVariable             dot         yuriShadow
syntaxString               monikaEye   ribbon
syntaxNumber               sayori      yuri
syntaxType                 monika      rule
syntaxOperator             natsuki     bowShadow
syntaxPunctuation          dot         yuriShadow
"

while read -r oc_key oc_dark oc_light; do
  need "opencode key $oc_key" "$oc_dark" "$oc_light"
done < <(awk 'NF == 3' <<<"$opencode_slots")

oc_defs=$(
  for name in "${pal_names[@]}"; do printf '%s\t#%s\n' "$name" "${pal[$name]}"; done |
    jq -Rn '[inputs | split("\t") | { key: .[0], value: .[1] }] | from_entries'
)
oc_theme=$(
  awk 'NF == 3 { print $1 "\t" $2 "\t" $3 }' <<<"$opencode_slots" |
    jq -Rn '[inputs | split("\t") | {
      key: .[0],
      value: (if .[1] == .[2] then .[1] else { dark: .[1], light: .[2] } end)
    }] | from_entries'
)
jq -n --argjson defs "$oc_defs" --argjson theme "$oc_theme" '{
  "$schema": "https://opencode.ai/theme.json",
  defs: $defs,
  theme: $theme
}' >"$out/ddlc-opencode.json"

echo "wrote, per variant, $out/{ddlc-kitty-VARIANT.conf,ddlc-btop-VARIANT.theme,ddlc-claude-code-VARIANT.json}"
echo "and $out/{ddlc.mplstyle,ddlc-dark.mplstyle,ddlc_cmaps.py,ddlc-report.css,ddlc-opencode.json}"
