#!/usr/bin/env bash
set -euo pipefail

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
out="$here/dist"
src="$here/src"
vendor="$here/vendor"

usage() {
  cat <<EOF
generate.sh — render the kitty, btop, matplotlib, Claude Code and opencode themes, the
web kit, the report stylesheet, the letter styles and the syntax table out of ddlc-palette

It writes dist/, committed for consumers without Nix: run it after the palette moves, or
after an edit to src/, and commit the result with the rendered files. It reads src/ and
vendor/ beside itself

  --light FILE     base16-ddlc-light.yaml   (or \$DDLC_BASE16_LIGHT)
  --dark FILE      base16-ddlc-dark.yaml    (or \$DDLC_BASE16_DARK)
  --palette FILE   palette.env              (or \$DDLC_PALETTE_ENV)
  --nerd FILE      DepartureMono.tar.xz     (or \$DDLC_NERD_DEPARTURE)

The schemes and the palette come from ddlc-palette, the archive from the Nerd Fonts release,
and nix develop puts each of them in the environment already. Without Nix, take them there:

  curl -sSLO https://raw.githubusercontent.com/rokokol/ddlc-palette/master/dist/base16-ddlc-dark.yaml
  curl -sSLO https://raw.githubusercontent.com/rokokol/ddlc-palette/master/dist/palette.env
  curl -sSLO https://github.com/ryanoasis/nerd-fonts/releases/latest/download/DepartureMono.tar.xz
EOF
}

declare -A scheme=(
  [light]="${DDLC_BASE16_LIGHT:-}"
  [dark]="${DDLC_BASE16_DARK:-}"
)
palette_env="${DDLC_PALETTE_ENV:-}"
nerd_archive="${DDLC_NERD_DEPARTURE:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --light)
      scheme[light]="${2:?file required}"
      shift 2
      ;;
    --dark)
      scheme[dark]="${2:?file required}"
      shift 2
      ;;
    --palette)
      palette_env="${2:?file required}"
      shift 2
      ;;
    --nerd)
      nerd_archive="${2:?file required}"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 1
      ;;
  esac
done

# The kitty and btop tables below name base16 slots, so resolve them once per variant. $V picks
# the variant
declare -A slot
for variant in light dark; do
  file="${scheme[$variant]}"
  [ -n "$file" ] || {
    echo "generate.sh: no $variant scheme — pass --$variant or set DDLC_BASE16_${variant^^}" >&2
    exit 1
  }
  n=0
  while read -r key hex; do
    slot["$variant/$key"]="$hex"
    n=$((n + 1))
  done < <(sed -n 's/^  \(base[0-9A-F][0-9A-F]\): "\(#[0-9A-F]\{6\}\)".*/\1 \2/p' "$file")
  # Sixteen slots or it is not a base16 scheme, and a half-read file would render a half-theme
  [ "$n" = 16 ] || {
    echo "generate.sh: $file has $n slots, want 16" >&2
    exit 1
  }
done
s() { printf '%s' "${slot["$V/$1"]}"; }

# The other themes have more roles than sixteen slots, so their tables name palette colours
# directly and resolve against the flat name=HEX form. The hex comes in bare — matplotlib wants
# it that way (its parser treats the rest of an rcparam value after a "#" as a comment, so a
# quoted "#BB5599" reads as an unterminated string and the whole cycler is silently discarded
# for the stock one) — and the JSON writers put the "#" back on
[ -n "$palette_env" ] || {
  echo "generate.sh: no palette — pass --palette or set DDLC_PALETTE_ENV" >&2
  exit 1
}
declare -A pal
pal_names=()
while read -r name hex; do
  pal[$name]="$hex"
  pal_names+=("$name")
done < <(sed -n 's/^\([A-Za-z][A-Za-z0-9]*\)=\([0-9A-F]\{6\}\)$/\1 \2/p' "$palette_env")
[ "${#pal_names[@]}" -gt 0 ] || {
  echo "generate.sh: $palette_env holds no name=HEX lines" >&2
  exit 1
}

# A table naming a colour the palette does not have is a typo or a rename that got away. Either
# would ship a theme with a hole in it, so refuse the whole run before writing any of it
need() { # <theme> <name>...
  local theme="$1" name
  shift
  for name in "$@"; do
    [[ $name == "-" || $name == "none" || -n ${pal[$name]:-} ]] || {
      echo "generate.sh: $theme names $name, which the palette does not have" >&2
      exit 1
    }
  done
}

mkdir -p "$out"
banner="Generated by generate.sh from ddlc-palette's base16 schemes — do not edit"
named_banner="Generated by generate.sh from ddlc-palette's colours — do not edit"

for V in light dark; do

  # Slot for slot the mapping tinted-theming/tinted-kitty uses, with one departure: it grounds
  # the selection in base03, which leaves base05 on it at 1.65:1 here, so base02 carries it.
  # The light column departs further, because the palette is polarised and one slot does not
  # read the same on both grounds. Bright black is base02 (natsuki) on paper at 1.4:1, and it
  # carries shell suggestions and dimmed output, so light takes base03 (jacket, 2.6:1). The
  # cursor, links, the active border and the active tab take base0E (plum), the colour of the
  # site's own links and download button; paper on plum holds 4.3:1
  kitty_slots="background             base00  base00
foreground             base05  base05
selection_background   base02  base02
selection_foreground   base05  base05
cursor                 base05  base0E
cursor_text_color      base00  base00
url_color              base04  base0E
active_border_color    base03  base0E
inactive_border_color  base01  base01
wayland_titlebar_color base00  base00
macos_titlebar_color   base00  base00
active_tab_background  base00  base0E
active_tab_foreground  base05  base00
inactive_tab_background base01 base01
inactive_tab_foreground base04 base04
tab_bar_background     base01  base01

color0                 base00  base00
color1                 base08  base08
color2                 base0B  base0B
color3                 base0A  base0A
color4                 base0D  base0D
color5                 base0E  base0E
color6                 base0C  base0C
color7                 base05  base05
color8                 base02  base03
color9                 base08  base08
color10                base0B  base0B
color11                base0A  base0A
color12                base0D  base0D
color13                base0E  base0E
color14                base0C  base0C
color15                base07  base07
color16                base09  base09
color17                base0F  base0F
color18                base01  base01
color19                base02  base02
color20                base04  base04
color21                base06  base06"
  col=2
  [[ $V == light ]] && col=3
  {
    echo "# $banner"
    echo "# vim:ft=kitty"
    echo "# Include this from kitty.conf: include ddlc-kitty-$V.conf"
    echo
    # A blank line in the table separates the chrome from the ANSI colours, as in the output
    while read -r line; do
      [ -n "$line" ] || {
        echo
        continue
      }
      read -r key slot_name <<<"$(awk -v c="$col" '{ print $1, $c }' <<<"$line")"
      echo "$key $(s "$slot_name")"
    done <<<"$kitty_slots"
  } >"$out/ddlc-kitty-$V.conf"

  # btop has no base16 template anywhere upstream, so this mapping is local. Meters that carry no
  # scale are one colour — btop reads that as a start with an empty mid and end
  {
    echo "# $banner"
    echo "# Drop into ~/.config/btop/themes/ and select it with color_theme=\"ddlc-$V\""
    echo
    echo "theme[main_bg]=\"$(s base00)\""
    echo "theme[main_fg]=\"$(s base05)\""
    echo "theme[title]=\"$(s base06)\""
    echo "theme[hi_fg]=\"$(s base0A)\""
    echo "theme[selected_bg]=\"$(s base02)\""
    echo "theme[selected_fg]=\"$(s base06)\""
    echo "theme[inactive_fg]=\"$(s base03)\""
    echo "theme[graph_text]=\"$(s base04)\""
    echo "theme[meter_bg]=\"$(s base01)\""
    echo "theme[proc_misc]=\"$(s base0B)\""
    echo "theme[cpu_box]=\"$(s base0D)\""
    echo "theme[mem_box]=\"$(s base0B)\""
    echo "theme[net_box]=\"$(s base0E)\""
    echo "theme[proc_box]=\"$(s base0C)\""
    echo "theme[div_line]=\"$(s base03)\""
    # Load rises through the palette's warm accents: green, then yellow, then red
    for gradient in temp cpu process; do
      echo "theme[${gradient}_start]=\"$(s base0B)\""
      echo "theme[${gradient}_mid]=\"$(s base0A)\""
      echo "theme[${gradient}_end]=\"$(s base08)\""
    done
    while read -r meter slot_name; do
      echo "theme[${meter}_start]=\"$(s "$slot_name")\""
      echo "theme[${meter}_mid]=\"\""
      echo "theme[${meter}_end]=\"\""
    done <<'METERS'
free base0B
cached base0C
available base0A
used base08
download base0D
upload base0E
METERS
  } >"$out/ddlc-btop-$V.theme"

done

# --- matplotlib -------------------------------------------------------------------------------
# matplotlib finds a named style by filename under stylelib/, so the file name is the API:
# plt.style.use("ddlc"). The module name is too — import ddlc_cmaps — hence its underscore

mpl_cycle_light="plum bow rule monikaEye yuri"
mpl_cycle_dark="plum bow rule"
# shellcheck disable=SC2086 # the cycles are word lists on purpose
need matplotlib paper ink jacket ash yuri dot pink sayoriEye skirt bow bowShadow sayori \
  $mpl_cycle_light $mpl_cycle_dark

mpl_cycler() {
  local sep='' cyc='' c
  for c in "$@"; do
    cyc+="$sep'${pal[$c]}'"
    sep=', '
  done
  printf "axes.prop_cycle:  cycler('color', [%s])\n" "$cyc"
}

mpl_colours() { # ground ink muted grid
  cat <<EOF
figure.facecolor:  ${pal[$1]}
savefig.facecolor: ${pal[$1]}
axes.facecolor:    ${pal[$1]}
axes.edgecolor:    ${pal[$4]}
grid.color:        ${pal[$4]}

text.color:        ${pal[$2]}
axes.labelcolor:   ${pal[$2]}
axes.titlecolor:   ${pal[$2]}
xtick.color:       ${pal[$3]}
ytick.color:       ${pal[$3]}
xtick.labelcolor:  ${pal[$2]}
ytick.labelcolor:  ${pal[$2]}
EOF
}

# No axes.grid in here: it would mean "on every axes", and a heatmap or an image draws above
# the grid whatever axisbelow says, so the lines end up cutting across the data. A chart that
# wants one calls ax.grid(axis="y") for the direction its values actually run.
# The face is Nunito, the prose face. matplotlib reads no variation axis, so a variable
# Nunito draws in its default instance, ExtraLight, and has no bold: the title stays
# normal, or every chart would log that it found no bold weight
mpl_common() {
  cat <<'EOF'
figure.dpi:          140
savefig.dpi:         140
savefig.bbox:        tight
font.family:         sans-serif
font.sans-serif:     Nunito, DejaVu Sans
font.size:           9
axes.titlesize:      11
axes.titleweight:    normal
axes.titlelocation:  left
axes.spines.top:     False
axes.spines.right:   False
axes.axisbelow:      True
grid.linewidth:      0.7
legend.frameon:      False
lines.linewidth:     1.8
EOF
}

{
  echo "# $named_banner"
  echo "# Copy into ~/.config/matplotlib/stylelib/ and select it: plt.style.use(\"ddlc\")"
  echo
  echo "# A chart assigns series from this list in order, and the order is the safety mechanism"
  echo "# rather than a taste: adjacent entries are what a stacked bar or a multi-line chart puts"
  echo "# side by side. Each neighbour pair clears deuteranopia and protanopia"
  echo "# (Machado-Oliveira-Fernandes 2009 at severity 1.0) by OKLab distance x100 >= 8, and"
  echo "# >= 15 unsimulated. Reordering is a visible change even though no colour moves"
  # shellcheck disable=SC2086 # the cycle is a word list on purpose
  mpl_cycler $mpl_cycle_light
  echo
  mpl_colours paper ink jacket ash
  echo
  mpl_common
} >"$out/ddlc.mplstyle"

{
  echo "# $named_banner"
  echo "# Copy into ~/.config/matplotlib/stylelib/ and select it: plt.style.use(\"ddlc-dark\")"
  echo
  echo "# Three series, not five. The palette is polarised — the same reason base16 draws"
  echo "# different accents per variant — and everything else either leaves the dark lightness"
  echo "# band or falls under 3:1 on ink"
  # shellcheck disable=SC2086 # the cycle is a word list on purpose
  mpl_cycler $mpl_cycle_dark
  echo
  mpl_colours ink paper jacket yuri
  echo
  mpl_common
} >"$out/ddlc-dark.mplstyle"

# A colormap is an object, not an rcparam, so it cannot live in a .mplstyle. Importing the
# module registers the four by name, after which they are strings like any built-in
cat >"$out/ddlc_cmaps.py" <<EOF
# $named_banner
"""DDLC colormaps for matplotlib, registered by name.

import ddlc_cmaps  # noqa: F401 — registers on import
plt.imshow(data, cmap="ddlc_seq")

Sequential runs one hue toward the foreground of its ground, so more-is-darker on paper and
more-is-lighter on ink. Diverging is two one-hue arms about a neutral middle, so "no
difference" reads as nothing at all; its midpoint is the only grey in each.
"""

from matplotlib.colors import LinearSegmentedColormap
from matplotlib import colormaps

_MAPS = {
    "ddlc_seq": ["#${pal[dot]}", "#${pal[pink]}", "#${pal[plum]}"],
    "ddlc_seq_dark": ["#${pal[plum]}", "#${pal[pink]}", "#${pal[dot]}"],
    "ddlc_div": [
        "#${pal[yuri]}",
        "#${pal[rule]}",
        "#${pal[ash]}",
        "#${pal[bow]}",
        "#${pal[bowShadow]}",
    ],
    "ddlc_div_dark": [
        "#${pal[sayoriEye]}",
        "#${pal[skirt]}",
        "#${pal[jacket]}",
        "#${pal[bow]}",
        "#${pal[sayori]}",
    ],
}

for _name, _colours in _MAPS.items():
    for _key, _steps in ((_name, _colours), (_name + "_r", _colours[::-1])):
        if _key not in colormaps:
            colormaps.register(LinearSegmentedColormap.from_list(_key, _steps))
EOF

# --- roles ------------------------------------------------------------------------------------
# Everything that is not a terminal reads this one table: the web kit, the report stylesheet,
# the letters and the Obsidian theme, which vendors ddlc-tokens.css. So a role is the same
# colour on every surface. The columns are dark and light, as in the tables above. A value is
# a palette colour, a role defined above it, a slot of the dark base16 scheme, "transparent",
# or "a@NN:b" for NN percent of a over b. The stylesheets carry the dark scheme alone, because
# the code window is dark on both sides.
# Where the web pages and the Obsidian theme disagreed, the Obsidian value is here: muted text
# mixes the jacket with the ink on paper and with the paper on ink, because the bare jacket
# reads 2.55:1 on paper. A role never takes the name of a palette colour, so a page can link
# palette.css and a stylesheet from here together.
# A kind role colours a note by its kind, as an Obsidian callout type does. Two kinds never
# share a hue. A link on ink is blush rather than the accent's pink, which reads dim beside
# white text. The dots are the polka-dot paper's, below, on the ground
ui_roles="
ground                ink                    paper
dots                  yuriShadow@75:ink      dot
text                  paper                  ink
muted                 jacket@75:paper        ink@55:jacket
faint                 jacket                 jacket
line                  yuri                   blush
line-live             plum                   pink
grid                  yuri@70:ink            ash
accent                pink                   plum
accent-live           blush                  pink
link                  blush                  plum
link-live             paper                  pink
on-accent             paper                  paper
panel                 ground@92:transparent  ground@92:transparent
selection             yuri@90:transparent    blush@80:transparent
highlight             plum@55:transparent    blush@85:transparent
code-ground           yuriShadow             dot
cloud                 yuriShadow             dot
danger                bow                    bow
ok                    monikaEye              monikaEye
switch-off            jacket@55:ink          jacket
popup-ground          dot                    dot@70:paper
popup-frame           blush                  blush
popup-text            ink                    ink
popup-accent          plum@70:ink            plum
tape                  pink@60:transparent    blush@70:transparent
board                 yuri@30:ink            dot@50:paper
board-shade           board@60:ink           board@80:jacket
board-frame           board-shade            dot
board-drop            blush                  blush
kind-note             sayoriEye              sayoriEye
kind-summary          rule                   rule
kind-tip              pink                   pink
kind-success          ok                     ok
kind-warning          sayori                 sayori
kind-danger           danger                 danger
kind-example          yuri                   yuri
kind-quote            jacket                 jacket
kind-experiment       ribbon                 ribbon
window-ground         base00                 base00
window-text           base05                 base05
window-bar            base01                 base01
window-border         base02                 base02
window-title          base05@80:base01       base05@80:base01
window-control        base05@14:base01       base05@14:base01
window-control-hover  base05@28:base01       base05@28:base01
window-control-live   base07                 base07
window-prompt         base0E                 base0E
window-selection      base02                 base02
window-caret          base05@65:transparent  base05@65:transparent
"

# One table of syntax colours for every editor and viewer: ddlc.nvim vendors ddlc-syntax.json,
# opencode reads it below, and the code window takes the dark column. The roles and the dark
# column are ddlc.nvim's own groups. A base16 slot here reads the scheme of its own column.
# Each role holds 3:1 on its variant's ground, so the dark column moves builtin off bow (2.8:1)
# to natsuki and delimiter off bowShadow (1.7:1) to ash, and the light column moves number off
# sayori (2.0:1) and type off monika (2.8:1) to the colours opencode already took there, and
# comment and quote to the muted role
syntax_slots="
comment     base03     muted
keyword     base0E     base0E
function    base0D     base0D
string      base0B     base0B
number      base09     yuri
type        base0A     rule
text        base05     base05
builtin     natsuki    base08
special     base0C     base0C
delimiter   ash        base0F
heading     base0D     base0D
link        base0D     base0D
url         base0C     base0C
link-label  base0E     base0E
raw         base0B     base0B
list        base0E     base0E
quote       base03     muted
"
syntax_floor=3

# The game menu's polka-dot paper, as ddlc.moe tiles it: a square tile holds two dots, at a
# quarter and at three quarters of it on both axes, each a fifth of the tile in radius. The
# sizes are CSS pixels; a surface that cannot repeat a tile draws the same grid at that size
polka_tile=120
polka_dot=$((polka_tile / 5))

# The faces, for the stylesheets and the letters alike. A letter cannot load a web font, so
# every stack names the faces a reader may have installed and ends in an honest fallback.
# Prose is Nunito, which the stylesheets carry; after it come the faces each system draws
# its own interface in. A heading is Doki where it is installed, since Doki may not be
# shared, and Nunito Black otherwise; a stylesheet reaches Black through the variable
# Nunito it carries, while a letter can only name a face, so the letter's stack differs
font_stacks="
prose           Nunito, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif
heading         Doki, Nunito, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif
heading-letter  Doki, 'Nunito Black', 'Segoe UI Black', 'Arial Black', sans-serif
data            'Departure Mono', 'DepartureMono Nerd Font Mono', 'DepartureMono Nerd Font', ui-monospace, 'SF Mono', Menlo, monospace
sans            system-ui, -apple-system, 'Segoe UI', sans-serif
"

kebab() { # monikaEye -> monika-eye, the spelling palette.css uses
  local s="$1" out="" c i
  for ((i = 0; i < ${#s}; i++)); do
    c="${s:i:1}"
    if [[ $c == [A-Z] ]]; then out+="-${c,,}"; else out+="$c"; fi
  done
  printf '%s' "$out"
}

declare -A pal_kebab
for name in "${pal_names[@]}"; do pal_kebab[$(kebab "$name")]=1; done

# NN percent of one six-digit hex over another, as an opaque six-digit hex
mix_hex() { # <fg> <bg> <share>
  local i
  for i in 0 2 4; do
    printf '%02X' $(((16#${1:i:2} * $3 + 16#${2:i:2} * (100 - $3) + 50) / 100))
  done
}

# WCAG contrast of two six-digit hex colours, two decimals
contrast() { # <hex> <hex>
  awk -v a="$1" -v b="$2" '
    function ch(h, i,   c) { c = index("0123456789ABCDEF", substr(h, i, 1)) * 16 - 16
      c += index("0123456789ABCDEF", substr(h, i + 1, 1)) - 1; c /= 255
      return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ^ 2.4 }
    function lum(h) { return 0.2126 * ch(h, 1) + 0.7152 * ch(h, 3) + 0.0722 * ch(h, 5) }
    BEGIN { x = lum(a); y = lum(b); if (x < y) { t = x; x = y; y = t }
      printf "%.2f", (x + 0.05) / (y + 0.05) }'
}

declare -A role
role_names=()
# An operand of a role value: a palette colour, a role already in the table, a base16 slot or
# "transparent". Anything else is a typo, and a typo would ship a stylesheet with a hole in it
role_operand() { # <where> <operand>
  [[ $2 == transparent || $2 =~ ^base0[0-9A-F]$ || -n ${pal[$2]:-} || -n ${role["dark/$2"]:-} ]] || {
    echo "generate.sh: $1 names $2, which is no palette colour, earlier role or base16 slot" >&2
    exit 1
  }
}
role_value() { # <where> <value>
  if [[ $2 == *@*:* ]]; then
    local share="${2#*@}"
    share="${share%%:*}"
    [[ $share =~ ^[1-9][0-9]?$ ]] || {
      echo "generate.sh: $1 reads $2, whose share is not 1 to 99" >&2
      exit 1
    }
    role_operand "$1" "${2%%@*}"
    role_operand "$1" "${2#*:}"
  else
    role_operand "$1" "$2"
  fi
}

while read -r r_name r_dark r_light; do
  [[ -z ${pal_kebab[$r_name]:-} ]] || {
    echo "generate.sh: the role $r_name has the name of a palette colour" >&2
    exit 1
  }
  role_value "role $r_name" "$r_dark"
  role_value "role $r_name" "$r_light"
  role["dark/$r_name"]="$r_dark"
  role["light/$r_name"]="$r_light"
  role_names+=("$r_name")
done < <(awk 'NF == 3' <<<"$ui_roles")

# The series continue the matplotlib cycles, so a chart and the table beside it agree. Dark
# has three; its fourth and fifth collapse into the muted grey, so a tail that was not folded
# into the three stays visible but stops pretending to be a series
read -r -a cycle_dark <<<"$mpl_cycle_dark"
read -r -a cycle_light <<<"$mpl_cycle_light"
for i in 0 1 2 3 4; do
  role["dark/series-$((i + 1))"]="${cycle_dark[i]:-jacket}"
  role["light/series-$((i + 1))"]="${cycle_light[i]}"
  role_names+=("series-$((i + 1))")
done

css_ref() { # <operand>
  if [[ $1 == transparent ]]; then
    printf 'transparent'
  elif [[ -n ${pal[$1]:-} ]]; then
    printf 'var(--ddlc-%s)' "$(kebab "$1")"
  else
    printf 'var(--ddlc-%s)' "$1"
  fi
}

css_value() { # <value>
  if [[ $1 == *@*:* ]]; then
    local share="${1#*@}"
    printf 'color-mix(in srgb, %s %s%%, %s)' "$(css_ref "${1%%@*}")" "${share%%:*}" "$(css_ref "${1#*:}")"
  else
    css_ref "$1"
  fi
}

# The opaque hex a value comes to in a variant; base16 slots read the scheme named by the
# third argument. A letter has no transparency to blend against, so transparent is refused
hex_of() { # <variant> <value> <scheme variant>
  local v="$2"
  if [[ $v == *@*:* ]]; then
    local share="${v#*@}"
    mix_hex "$(hex_of "$1" "${v%%@*}" "$3")" "$(hex_of "$1" "${v#*:}" "$3")" "${share%%:*}"
  elif [[ $v =~ ^base0[0-9A-F]$ ]]; then
    printf '%s' "${slot["$3/$v"]#\#}"
  elif [[ -n ${pal[$v]:-} ]]; then
    printf '%s' "${pal[$v]}"
  elif [[ -n ${role["$1/$v"]:-} ]]; then
    hex_of "$1" "${role["$1/$v"]}" "$3"
  else
    echo "generate.sh: $v has no opaque hex" >&2
    return 1
  fi
}

# Syntax roles: the light column may name a role, the dark one may not, because the code
# window reads the dark column under a page that may be light
declare -A syn
syn_names=()
while read -r s_name s_dark s_light; do
  for s_column in dark light; do
    s_value="$s_dark"
    [[ $s_column == light ]] && s_value="$s_light"
    [[ $s_value =~ ^base0[0-9A-F]$ || -n ${pal[$s_value]:-} ||
      ($s_column == light && -n ${role["light/$s_value"]:-}) ]] || {
      echo "generate.sh: syntax $s_name names $s_value in the $s_column column, which it cannot read" >&2
      exit 1
    }
  done
  syn["dark/$s_name"]=$(hex_of dark "$s_dark" dark)
  syn["light/$s_name"]=$(hex_of light "$s_light" light)
  syn["css/$s_name"]=$(css_ref "$s_dark")
  for V in dark light; do
    ratio=$(contrast "${syn["$V/$s_name"]}" "$(hex_of "$V" ground dark)")
    awk -v r="$ratio" -v f="$syntax_floor" 'BEGIN { exit !(r >= f) }' || {
      echo "generate.sh: syntax $s_name reads $ratio:1 on the $V ground, under $syntax_floor:1" >&2
      exit 1
    }
  done
  syn_names+=("$s_name")
done < <(awk 'NF == 3' <<<"$syntax_slots")

declare -A font
while read -r f_name f_stack; do
  font[$f_name]="$f_stack"
done < <(awk 'NF >= 2' <<<"$font_stacks")

# The roles as custom properties, two spaces in. A role that reads the same on both sides is
# one value; the rest are light-dark(), which the element's color-scheme resolves
css_roles() {
  local r
  for r in "${role_names[@]}"; do
    if [[ ${role["dark/$r"]} == "${role["light/$r"]}" ]]; then
      printf '  --ddlc-%s: %s;\n' "$r" "$(css_value "${role["dark/$r"]}")"
    else
      printf '  --ddlc-%s: light-dark(%s, %s);\n' "$r" \
        "$(css_value "${role["light/$r"]}")" "$(css_value "${role["dark/$r"]}")"
    fi
  done
  for r in "${syn_names[@]}"; do
    printf '  --ddlc-syntax-%s: %s;\n' "$r" "${syn["css/$r"]}"
  done
  printf '  --ddlc-polka-tile: %spx;\n  --ddlc-polka-dot: %spx;\n' "$polka_tile" "$polka_dot"
}

# What a self-contained stylesheet starts with: the palette, the dark base16 scheme, the faces
# and the roles, then the switch between the variants. The system decides until data-theme on
# the root pins a side
css_head() {
  local name f
  echo ":root {"
  for name in "${pal_names[@]}"; do printf '  --ddlc-%s: #%s;\n' "$(kebab "$name")" "${pal[$name]}"; done
  for name in $(printf '%s\n' "${!slot[@]}" | sed -n 's|^dark/||p' | sort); do
    printf '  --ddlc-%s: %s;\n' "$name" "${slot["dark/$name"]}"
  done
  for f in prose heading data sans; do printf '  --ddlc-font-%s: %s;\n' "$f" "${font[$f]}"; done
  css_roles
  echo "  color-scheme: light dark;"
  echo "}"
  echo
  echo ":root[data-theme=\"light\"] { color-scheme: light; }"
  echo ":root[data-theme=\"dark\"] { color-scheme: dark; }"
}

# Every name a stylesheet in src/ reads must exist, or the browser drops the declaration in
# silence. And a name it defines must not be a palette colour, or it would repaint palette.css
css_known() { # <name without --ddlc->
  local n="$1"
  [[ -n ${pal_kebab[$n]:-} || $n =~ ^base0[0-9A-F]$ || -n ${role["dark/$n"]:-} ]] && return
  [[ $n == syntax-* && -n ${syn["dark/${n#syntax-}"]:-} ]] && return
  [[ $n == font-* && -n ${font[${n#font-}]:-} ]] && return
  return 1
}
for source in "$src"/*.css; do
  defined=$(sed -n 's/^ *--ddlc-\([a-z0-9-]*\):.*/\1/p' "$source")
  while read -r name; do
    [[ -n $name && -n ${pal_kebab[$name]:-} ]] || continue
    echo "generate.sh: $source defines --ddlc-$name, the name of a palette colour" >&2
    exit 1
  done <<<"$defined"
  while read -r name; do
    css_known "$name" || grep -qx "$name" <<<"$defined" || {
      echo "generate.sh: $source reads --ddlc-$name, which nothing defines" >&2
      exit 1
    }
  done < <(grep -o 'var(--ddlc-[a-z0-9-]*' "$source" | sed 's/^var(--ddlc-//' | sort -u)
done

# The roles alone, for a theme that brings its own palette and selectors — Obsidian's
{
  echo "/* $named_banner"
  echo "   The DDLC roles as custom properties, with no palette and no selectors of an"
  echo "   application. It reads the palette's --ddlc-* colours and the dark base16 slots"
  echo "   --ddlc-base00 to --ddlc-base0F from the page, and a role that differs between"
  echo "   the variants is light-dark(), so the element's color-scheme picks the side */"
  echo
  echo ":root {"
  css_roles
  echo "}"
} >"$out/ddlc-tokens.css"

# The web kit and the report stylesheet: each one file a page links, carrying everything it
# reads. They share the head and src/base.css, and add their own elements
for sheet in ui report; do
  {
    echo "/* $named_banner */"
    echo
    # the sheet's own opening comment says what it is for
    sed -n '1,/\*\//p' "$src/$sheet.css"
    echo
    css_head
    echo
    sed '1,/\*\//d' "$src/base.css"
    echo
    sed '1,/\*\//d' "$src/$sheet.css"
  } >"$out/ddlc-$sheet.css"
done

# The scripts are not generated from anything, only copied, so a consumer vendors the whole
# kit out of one directory
for script in theme cloud; do
  {
    echo "// Copied by generate.sh from src/$script.js — do not edit"
    cat "$src/$script.js"
  } >"$out/ddlc-$script.js"
done
for file in "$vendor"/departure-mono/*; do
  cat "$file" >"$out/$(basename "$file")"
done

# Nunito comes as variable TrueType, every script and weight it has. fonttools packs it into
# WOFF2 whole, at about two fifths of the size, so a page that carries it loses no script.
# The packing is byte-stable for the same input and fonttools, so dist/ stays checkable
command -v fonttools >/dev/null || {
  echo "generate.sh: fonttools is missing; nix develop puts it in the environment" >&2
  exit 1
}
for style in "" -Italic; do
  fonttools ttLib.woff2 compress -o "$out/Nunito$style.woff2" \
    "$vendor/nunito/Nunito$style-wght.ttf" >/dev/null
done
cat "$vendor/nunito/Nunito-LICENSE.txt" >"$out/Nunito-LICENSE.txt"

# Departure Mono with the Nerd Fonts icons, for code that shows them. The fonts are only in
# the Nerd Fonts release archive, not in that repository's tree, so the archive is an input
# like the palette. Its LICENSE is the font's, and its README carries the icon sets' licences,
# so both go beside the font unchanged. The Mono build keeps every icon one cell wide
[ -n "$nerd_archive" ] || {
  echo "generate.sh: no Nerd Fonts archive — pass --nerd or set DDLC_NERD_DEPARTURE" >&2
  exit 1
}
nerd=$(mktemp -d "${TMPDIR:-/tmp}/ddlc-nerd.XXXXXX")
trap 'rm -rf "$nerd"' EXIT
tar -xJf "$nerd_archive" -C "$nerd" DepartureMonoNerdFontMono-Regular.otf LICENSE README.md
fonttools ttLib.woff2 compress -o "$out/DepartureMonoNerdFontMono-Regular.woff2" \
  "$nerd/DepartureMonoNerdFontMono-Regular.otf" >/dev/null
cat "$nerd/LICENSE" >"$out/DepartureMonoNerdFont-LICENSE.txt"
cat "$nerd/README.md" >"$out/DepartureMonoNerdFont-README.md"

# --- letters ----------------------------------------------------------------------------------
# A letter cannot use var(): Gmail drops any declaration that carries one. So a letter gets
# literal styles, each a ready value for a style attribute, with the light roles and the faces
# already in them. A name in braces is a light role or a face. The sizes follow the report
# stylesheet; the inform block is the popup the report draws, square and thick-framed
mail_styles="
page          background:{ground};color:{text};font-family:{prose};line-height:1.55;padding:28px 20px 48px
column        max-width:736px;margin:0 auto
h1            margin:0;padding-bottom:6px;border-bottom:2px solid {line};font-family:{heading-letter};font-size:27px;line-height:1.25;font-weight:normal;color:{text}
h2            margin:32px 0 8px;font-family:{heading-letter};font-size:19px;line-height:1.25;font-weight:normal;color:{text}
h3            margin:18px 0 4px;font-family:{heading-letter};font-size:15px;line-height:1.3;font-weight:normal;color:{text}
sub           margin:2px 0 10px;font-size:13px;color:{muted}
p             margin:8px 0;font-size:14px;line-height:1.55;color:{text}
list          margin:6px 0;padding-left:20px;font-size:14px;line-height:1.6;color:{text}
item          margin:3px 0
table         border-collapse:collapse;width:100%;margin:6px 0 4px
th            padding:6px 18px 6px 0;border-bottom:1px solid {muted};text-align:left;font-size:11px;font-family:{data};font-weight:normal;color:{muted}
td            padding:6px 18px 6px 0;border-bottom:1px solid {grid};font-size:14px;font-family:{prose};color:{text}
td-data       padding:6px 18px 6px 0;border-bottom:1px solid {grid};font-size:12px;font-family:{data};color:{text}
td-cell       padding:6px 18px 6px 0;border-bottom:1px solid {grid};vertical-align:middle
kpi           border-collapse:collapse;margin:2px 0
kpi-cell      padding:14px 28px 14px 0;vertical-align:top
kpi-label     font-size:13px;font-family:{prose};color:{muted}
kpi-value     font-size:24px;line-height:1.3;font-family:{data};color:{text}
meter         border-collapse:separate;border-spacing:2px 0;width:100%;max-width:320px
meter-cell    height:10px;font-size:0;line-height:0
inform        margin:18px 0;padding:20px 24px;border:6px solid {popup-frame};background:{popup-ground};color:{popup-text};text-align:center
inform-title  font-family:{heading-letter};font-size:17px;font-weight:normal
inform-list   margin:8px 0 0;padding:0;list-style:none;font-size:14px;line-height:1.6
inform-item   margin:5px 0
details       margin:16px 0
summary       font-family:{heading-letter};font-size:16px;font-weight:normal;color:{text};cursor:pointer
journal       margin-top:8px;padding:12px 16px;border-radius:4px;background:{code-ground};font-family:{data};font-size:12px
journal-line  padding:2px 0;color:{text}
divider       margin-top:32px;border-top:2px solid {line}
image         display:block;max-width:100%;height:auto;margin:10px 0 4px
"

# The light roles that come to an opaque colour; a window role reads the dark scheme and a
# translucent one has nothing to blend against in a letter, so neither is offered
declare -A mail_colour
mail_colour_names=()
for r in "${role_names[@]}"; do
  [[ ${role["light/$r"]} != *transparent* && ${role["light/$r"]} != *base0* && $r != window-* ]] || continue
  mail_colour[$r]=$(hex_of light "$r" light)
  mail_colour_names+=("$r")
done

mail_fill() { # <style>
  local s="$1" key
  while [[ $s =~ \{([a-z0-9-]+)\} ]]; do
    key="${BASH_REMATCH[1]}"
    if [[ -n ${font[$key]:-} ]]; then
      s="${s//"{$key}"/${font[$key]}}"
    elif [[ -n ${mail_colour[$key]:-} ]]; then
      s="${s//"{$key}"/#${mail_colour[$key]}}"
    else
      echo "generate.sh: the letter style reads {$key}, which is no light role or face" >&2
      exit 1
    fi
  done
  printf '%s' "$s"
}

# Filled before the pipe below: an exit inside a substitution there would not stop the run
mail_rows=()
while read -r m_name m_style; do
  m_filled=$(mail_fill "$m_style")
  mail_rows+=("$(printf 'styles\t%s\t%s' "$m_name" "$m_filled")")
done < <(awk 'NF' <<<"$mail_styles")

{
  for r in "${mail_colour_names[@]}"; do printf 'colors\t%s\t#%s\n' "$r" "${mail_colour[$r]}"; done
  for f in prose data; do printf 'fonts\t%s\t%s\n' "$f" "${font[$f]}"; done
  printf 'fonts\theading\t%s\n' "${font["heading-letter"]}"
  printf '%s\n' "${mail_rows[@]}"
} | jq -Rn --arg banner "$named_banner" '
  [inputs | split("\t")] as $rows
  | { _generated: $banner }
    + ([$rows | group_by(.[0])[] | { key: .[0][0], value: (map({ key: .[1], value: .[2] }) | from_entries) }]
       | from_entries)' >"$out/ddlc-mail.json"

# --- syntax -----------------------------------------------------------------------------------
for name in "${syn_names[@]}"; do
  printf '%s\t#%s\t#%s\n' "$name" "${syn["dark/$name"]}" "${syn["light/$name"]}"
done | jq -Rn --arg banner "$named_banner" '
  [inputs | split("\t")] as $rows
  | { _generated: $banner,
      dark: ($rows | map({ key: .[0], value: .[1] }) | from_entries),
      light: ($rows | map({ key: .[0], value: .[2] }) | from_entries) }' >"$out/ddlc-syntax.json"

# --- roles as data ------------------------------------------------------------------------------
# The roles for a theme without CSS, such as a rofi window: every role a hex per variant, and the
# paper's grid. A role laid over transparent becomes #RRGGBBAA. The window roles read the dark
# scheme on both sides, as the stylesheets do
role_hex() { # <variant> <value>
  if [[ $2 =~ ^(.+)@([0-9]+):transparent$ ]]; then
    printf '%s%02X' "$(hex_of "$1" "${BASH_REMATCH[1]}" dark)" $(((BASH_REMATCH[2] * 255 + 50) / 100))
  else
    hex_of "$1" "$2" dark
  fi
}
# Filled before the pipe below: an exit inside a substitution there would not stop the run
role_rows=()
for r in "${role_names[@]}"; do
  r_dark=$(role_hex dark "${role["dark/$r"]}") || exit 1
  r_light=$(role_hex light "${role["light/$r"]}") || exit 1
  role_rows+=("$(printf '%s\t#%s\t#%s' "$r" "$r_dark" "$r_light")")
done
printf '%s\n' "${role_rows[@]}" | jq -Rn --arg banner "$named_banner" \
  --argjson tile "$polka_tile" --argjson dot "$polka_dot" '
  [inputs | split("\t")] as $rows
  | { _generated: $banner,
      polka: { tile: $tile, dot: $dot },
      dark: ($rows | map({ key: .[0], value: .[1] }) | from_entries),
      light: ($rows | map({ key: .[0], value: .[2] }) | from_entries) }' >"$out/ddlc-roles.json"

# --- Claude Code ------------------------------------------------------------------------------
# Claude Code reads a theme from ~/.claude/themes/<slug>.json: a base theme plus overrides, and
# it drops any key its version does not know without saying so. A slot reading "-" keeps
# whatever the base theme paints, because the palette holds nothing for it: the site ships no
# light green, so the light variant cannot colour an added line.
# The dark variant leans into the same slots ddlc.nvim draws from base16 dark: blush for the
# page text, neon pink for the frames and modes, sayoriEye and monikaEye for the cold and the
# green accents. The light variant sits on the colours that actually read on paper — the warm
# pastels fall under 3:1 there, so plum carries the claude identity and bowShadow the warning.
# Contrast holds every foreground slot: on ink, blush 10.3:1, natsuki 10.0, sayoriEye 9.2,
# sayori 8.1, monikaEye 7.3, jacket 6.2, monika 5.8, pink 5.6, plum 3.7, rule 3.2; on paper,
# yuriShadow 15.3, ribbon 6.2, bow 5.8, skirt 5.7, rule 5.0, plum 4.3
# A few slots are backgrounds under text the theme does not own. clawd_background fills the eye
# cells beside half-blocks that show the terminal's own background, so it takes that background
# (ink, paper), or the eyes get a visible frame. The diff word slots sit under the syntax theme's
# text, which is dark on a light terminal, so the light column takes the light monikaEye (7.0:1
# against yuriShadow) and monika (5.5). selectionBg is a cold blue, as in the built-in themes:
# the pinks and purples fill the rest of the theme, and a selection in them disappears
claude_code_slots="
text                                  blush       yuriShadow
inverseText                           ink         paper
inactive                              jacket      jacket
inactiveShimmer                       ash         ash
subtle                                natsuki     jacket
promptBorder                          pink        blush
promptBorderShimmer                   blush       pink
claude                                sayori      plum
claudeShimmer                         natsuki     pink
claudeBlue_FOR_SYSTEM_SPINNER         rule        skirt
claudeBlueShimmer_FOR_SYSTEM_SPINNER  sayoriEye   rule
clawd_body                            bow         bow
clawd_background                      ink         paper
permission                            sayoriEye   skirt
permissionShimmer                     rule        rule
suggestion                            rule        rule
remember                              pink        plum
ide                                   sayoriEye   skirt
autoAccept                            pink        plum
autoAcceptShimmer                     blush       pink
skill                                 plum        plum
merged                                plum        plum
effortUltra                           pink        pink
bashBorder                            pink        pink
planMode                              monikaEye   ribbon
success                               monikaEye   ribbon
warning                               monika      bowShadow
warningShimmer                        sayori      monika
error                                 bow         bow
diffAdded                             ribbon      -
diffRemoved                           bowShadow   -
diffAddedWord                         monikaEye   monikaEye
diffRemovedWord                       bow         monika
selectionBg                           skirt       sayoriEye
userMessageBackground                 yuriShadow  dot
userMessageBackgroundHover            yuri        blush
composerSidebarBackground             yuriShadow  dot
bashMessageBackgroundColor            yuriShadow  dot
memoryBackgroundColor                 yuriShadow  dot
rate_limit_fill                       pink        plum
rate_limit_empty                      yuriShadow  blush
fastMode                              sayori      plum
fastModeShimmer                       natsuki     pink
briefLabelYou                         sayoriEye   skirt
briefLabelClaude                      sayori      plum
red_FOR_SUBAGENTS_ONLY                bow         bow
orange_FOR_SUBAGENTS_ONLY             sayori      sayori
yellow_FOR_SUBAGENTS_ONLY             monika      monika
green_FOR_SUBAGENTS_ONLY              monikaEye   ribbon
cyan_FOR_SUBAGENTS_ONLY               sayoriEye   rule
blue_FOR_SUBAGENTS_ONLY               rule        skirt
purple_FOR_SUBAGENTS_ONLY             plum        yuri
pink_FOR_SUBAGENTS_ONLY               natsuki     pink
professionalBlue                      skirt       skirt
chromeYellow                          monika      monika
"

while read -r cc_slot cc_dark cc_light; do
  need "claude-code slot $cc_slot" "$cc_dark" "$cc_light"
done < <(awk 'NF == 3' <<<"$claude_code_slots")

# JSON takes no comment, so the banner goes in a field. Claude Code reads name, base and
# overrides and ignores the rest, so it costs nothing to say where the file came from
for variant in dark light; do
  col=2
  [[ $variant == light ]] && col=3
  awk -v c="$col" 'NF == 3 && $c != "-" { print $1 "\t" $c }' <<<"$claude_code_slots" |
    while read -r cc_slot cc_name; do printf '%s\t#%s\n' "$cc_slot" "${pal[$cc_name]}"; done |
    jq -Rn --arg banner "$named_banner" --arg name "DDLC $variant" --arg base "$variant" '{
      _generated: $banner,
      name: $name,
      base: $base,
      overrides: ([inputs | split("\t") | { key: .[0], value: .[1] }] | from_entries)
    }' >"$out/ddlc-claude-code-$variant.json"
done

# --- opencode ---------------------------------------------------------------------------------
# opencode takes one file for both variants: a value is either one colour or {dark, light}, and
# a string that is not a hex is a reference into defs — so defs carries the palette by name and
# the theme reads like the tables above. Its schema allows nothing extra (additionalProperties
# is false at the top and in theme), so there is no banner field and no key beyond the schema's
# own; defs naming the palette is the provenance the file carries. "none" is the schema's word
# for the terminal's own colour. The light column stays off the warm pastels — they fall under
# 3:1 on paper — and the dark one keeps its quiet roles a step brighter than claude-code's,
# because opencode paints whole panels with them
# A diff line's text is the syntax theme's, so only its background tells an added line from a
# removed one. The palette holds no pale green, and a full monikaEye or monika leaves plum at
# 2.0:1 and 1.6:1. So the light diff backgrounds read "name@NN": NN percent of the palette colour
# over the variant's background, mixed here into an opaque hex: monikaEye@20 is #E4F3D6, where
# plum keeps 3.7:1 and yuriShadow 13.2:1. An alpha hex would blend in opencode instead, but over
# the dot of the tool panel the diff sits in, where green turns beige. Context lines stay on
# that dot, as paper there opens the panel into the page. A pale red mix sits too close to dot,
# so removed lines take natsuki: 17 ΔE from dot, plum 2.7:1, yuriShadow 9.6:1
opencode_slots="
primary                    pink        plum
secondary                  sayoriEye   skirt
accent                     sayori      plum
error                      bow         bow
warning                    monika      bowShadow
success                    monikaEye   ribbon
info                       sayoriEye   skirt
text                       dot         yuriShadow
textMuted                  natsuki     jacket
selectedListItemText       paper       paper
background                 ink         paper
backgroundPanel            yuriShadow  dot
backgroundElement          yuri        natsuki
border                     jacket      jacket
borderActive               pink        plum
borderSubtle               yuri        ash
diffAdded                  paper       ribbon
diffRemoved                paper       bowShadow
diffContext                jacket      jacket
diffHunkHeader             jacket      jacket
diffHighlightAdded         monikaEye   ribbon
diffHighlightRemoved       bow         bowShadow
diffAddedBg                ribbon      monikaEye@20
diffRemovedBg              bowShadow   natsuki
diffContextBg              none        none
diffLineNumber             jacket      jacket
diffAddedLineNumberBg      ribbon      monikaEye@20
diffRemovedLineNumberBg    bowShadow   natsuki
markdownText               =text       =text
markdownHeading            =heading    =heading
markdownLink               =url        =url
markdownLinkText           =link       =link
markdownCode               =raw        =raw
markdownBlockQuote         =quote      =quote
markdownEmph               =text       =text
markdownStrong             =text       =text
markdownHorizontalRule     yuriShadow  ash
markdownListItem           =list       =list
markdownListEnumeration    =list       =list
markdownImage              =url        =url
markdownImageText          =link       =link
markdownCodeBlock          =text       =text
syntaxComment              =comment    =comment
syntaxKeyword              =keyword    =keyword
syntaxFunction             =function   =function
syntaxVariable             =text       =text
syntaxString               =string     =string
syntaxNumber               =number     =number
syntaxType                 =type       =type
syntaxOperator             =text       =text
syntaxPunctuation          =text       =text
"

while read -r oc_key oc_dark oc_light; do
  for oc_value in "$oc_dark" "$oc_light"; do
    if [[ $oc_value == =* ]]; then
      [[ -n ${syn["dark/${oc_value#=}"]:-} ]] || {
        echo "generate.sh: opencode key $oc_key reads $oc_value, which is no syntax role" >&2
        exit 1
      }
      continue
    fi
    need "opencode key $oc_key" "${oc_value%@*}"
    [[ $oc_value != *@* || $oc_value =~ @([1-9][0-9]?)$ ]] || {
      echo "generate.sh: opencode key $oc_key reads $oc_value, whose share is not 1 to 99" >&2
      exit 1
    }
  done
done < <(awk 'NF == 3' <<<"$opencode_slots")

oc_background() { # <dark|light>
  awk -v c="$([[ $1 == light ]] && echo 3 || echo 2)" '$1 == "background" { print $c }' <<<"$opencode_slots"
}

# A def name stays a reference; "name@NN" becomes the opaque hex of NN percent of the def over
# the variant's background; "=role" is the syntax table's colour, by its def name where the
# palette has it
oc_value() { # <dark|light> <name | name@NN | =role>
  if [[ $2 == =* ]]; then
    local hex="${syn["$1/${2#=}"]}" name
    for name in "${pal_names[@]}"; do
      [[ ${pal[$name]} == "$hex" ]] && {
        printf '%s' "$name"
        return
      }
    done
    printf '#%s' "$hex"
  elif [[ $2 == *@* ]]; then
    printf '#%s' "$(mix_hex "${pal[${2%@*}]}" "${pal[$(oc_background "$1")]}" "${2#*@}")"
  else
    printf '%s' "$2"
  fi
}

oc_defs=$(
  for name in "${pal_names[@]}"; do printf '%s\t#%s\n' "$name" "${pal[$name]}"; done |
    jq -Rn '[inputs | split("\t") | { key: .[0], value: .[1] }] | from_entries'
)
oc_theme=$(
  awk 'NF == 3' <<<"$opencode_slots" |
    while read -r oc_key oc_dark oc_light; do
      printf '%s\t%s\t%s\n' "$oc_key" "$(oc_value dark "$oc_dark")" "$(oc_value light "$oc_light")"
    done |
    jq -Rn '[inputs | split("\t") | {
      key: .[0],
      value: (if .[1] == .[2] then .[1] else { dark: .[1], light: .[2] } end)
    }] | from_entries'
)
jq -n --argjson defs "$oc_defs" --argjson theme "$oc_theme" '{
  "$schema": "https://opencode.ai/theme.json",
  defs: $defs,
  theme: $theme
}' >"$out/ddlc-opencode.json"

echo "wrote, per variant, $out/{ddlc-kitty-VARIANT.conf,ddlc-btop-VARIANT.theme,ddlc-claude-code-VARIANT.json}"
echo "and $out/{ddlc.mplstyle,ddlc-dark.mplstyle,ddlc_cmaps.py,ddlc-opencode.json}"
echo "and $out/{ddlc-tokens.css,ddlc-ui.css,ddlc-report.css,ddlc-mail.json,ddlc-syntax.json,ddlc-roles.json,ddlc-theme.js,ddlc-cloud.js}"
